@CyrusDemo_HostAddress = http://localhost:5216

POST {{CyrusDemo_HostAddress}}/tracks
Content-Type: application/json
Accept: application/json

{
  "trackId": "e03edc36-d5fb-4922-8ead-26a901c509f5",
  "title": "You got it",
  "artist": "Roy Orbison",
  "fileName": "you-got-it.mp3",
  "audioFormat": 0
}

###

POST {{CyrusDemo_HostAddress}}/tracks
Content-Type: application/json
Accept: application/json

{
  "trackId": "e03edc36-d5fb-4922-8ead-26a901c509f7",
  "title": "In the name of love",
  "artist": "U2",
  "fileName": "in-the-name-of-love.mp3",
  "audioFormat": 1
}

###

GET {{CyrusDemo_HostAddress}}/tracks
Content-Type: application/json
Accept: application/json

###

GET {{CyrusDemo_HostAddress}}/tracks/e03edc36-d5fb-4922-8ead-26a901c509f7
Content-Type: application/json
Accept: application/json

###

PUT {{CyrusDemo_HostAddress}}/tracks/e03edc36-d5fb-4922-8ead-26a901c509f7
Content-Type: application/json
Accept: application/json

{
  "title": "Pride (In the name of love)",
  "artist": "U2",
  "fileName": "in-the-name-of-love.mp3",
  "audioFormat": 0
}

###

PUT {{CyrusDemo_HostAddress}}/tracks2/e03edc36-d5fb-4922-8ead-26a901c509f7
Content-Type: application/json
Accept: application/json

{
  "title": "Pride (In the name of love)",
  "artist": "U2",
  "fileName": "in-the-name-of-love.mp3",
  "audioFormat": 0
}


###

GET {{CyrusDemo_HostAddress}}/tracks/e03edc36-d5fb-4922-8ead-26a901c509f7/mp3
Content-Type: application/json
Accept: application/json


