using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text.RegularExpressions;

namespace NForza.Generators;

public class TemplateEngine(Assembly assembly, string folderName)
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1035:Do not use APIs banned for analyzers", Justification = "<Pending>")]
    public string ReplaceInResourceTemplate(string templateName, Dictionary<string, string> replacements)
    {
        string template = EmbeddedResourceReader.GetResource(assembly, folderName, templateName);
        foreach (var replacement in replacements)
        {
            template = template.Replace("% " + replacement.Key + " %", replacement.Value);
        }
        ThrowIfTemplateHasUnresolvedMarkers(template);
        string generatorName = assembly.GetName().Name;
        return $"// Do not modify. This file is auto-generated by {generatorName}{Environment.NewLine}{template}";
    }

    private void ThrowIfTemplateHasUnresolvedMarkers(string template)
    {
        Regex regex = new Regex("% [a-zA-Z0-9_]{1,30} %");
        MatchCollection matches = regex.Matches(template);
        if (matches.Count > 0)
        {
            throw new InvalidOperationException($"The template has unresolved markers: {string.Join(", ", matches.Cast<Match>().Select(m => m.Value).ToList())}");
        }
    }
}
