// <auto-generated/>
using System;
using Microsoft.Extensions.DependencyInjection;

namespace NForza.Cqrs;

public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddCqrs(this IServiceCollection services, Action<CqrsOptions>? options = null)
    {
        options?.Invoke(new CqrsOptions(services));
        services.AddSingleton<ICommandDispatcher, CommandDispatcher>();
        services.AddSingleton<ICommandBus, LocalCommandBus>(); 
        services.AddSingleton<IEventBus, EventBus>(); 
        services.AddSingleton(BuildHandlerDictionary());
        % RegisterTypes %
        return services;
    }

    public static CommandHandlerDictionary BuildHandlerDictionary()
    {
        var handlers = new CommandHandlerDictionary();
        % RegisterHandlers %
        return handlers;
    }
}