
name: Build examples

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  PROJECT_FOLDER: ./examples
  MASSTRANSIT_FOLDER: MassTransit/MassTransit.sln
  SIGNALR_FOLDER: SignalR/CyrusSignalR/CyrusSignalR.sln
  TRACKS_FOLDER: TracksDemo/TracksDemo.sln
  
jobs:
  build_masstransit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_FOLDER }}/${{ env.MASSTRANSIT_FOLDER }}
    - name: Build
      run: dotnet build --no-restore ${{ env.PROJECT_FOLDER }}/${{ env.MASSTRANSIT_FOLDER }}
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{ env.PROJECT_FOLDER }}/${{ env.MASSTRANSIT_FOLDER }}
  build_signalr:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_FOLDER }}/${{ env.SIGNALR_FOLDER }}
    - name: Build
      run: dotnet build --no-restore ${{ env.PROJECT_FOLDER }}/${{ env.SIGNALR_FOLDER }}
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{ env.PROJECT_FOLDER }}/${{ env.SIGNALR_FOLDER }}
  build_tracks:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_FOLDER }}/${{ env.TRACKS_FOLDER }}
    - name: Build
      run: dotnet build --no-restore ${{ env.PROJECT_FOLDER }}/${{ env.TRACKS_FOLDER }}
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{ env.PROJECT_FOLDER }}/${{ env.TRACKS_FOLDER }}
