name: Build NForza.Cyrus

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Install NUKE Global Tool
      run: dotnet tool install Nuke.GlobalTool --global
    - name: Run Nuke Test
      run: nuke test
