name: Build MassTransit example

on:
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_FOLDER: ./examples/Cyrus.MassTransit

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_FOLDER }}
    - name: Build
      run: dotnet build --no-restore ${{ env.PROJECT_FOLDER }}
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{ env.PROJECT_FOLDER }}
