name: Build NForza.Cyrus.TypescriptGenerate

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore "./src/NForza.Cyrus.TypescriptGenerate/NForza.Cyrus.TypescriptGenerate.csproj"
    - name: Build
      run: dotnet build --no-restore "./src/NForza.Cyrus.TypescriptGenerate/NForza.Cyrus.TypescriptGenerate.csproj"
    - name: Test
      run: dotnet test --no-build --verbosity normal "./src/NForza.Cyrus.TypescriptGenerate/NForza.Cyrus.TypescriptGenerate.csproj"
