name: Publish NuGet Package

on:
  workflow_dispatch:
  push:
    branches:
      - main  

env:
  PACKAGE_VERSION: 1.0.1

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore "./NForza.Cyrus.sln"

    - name: Build the project
      run: dotnet build --configuration Release "./NForza.Cyrus.sln" /p:PackageVersion=$PACKAGEVERSION

    - name: Copy Packages to output
      run: |
        $OutputFolder = "./output"
        if (-not (Test-Path -Path $OutputFolder)) {
            New-Item -ItemType Directory -Path $OutputFolder
        }
        
        # Find all .nupkg files in the current directory and subfolders
        Get-ChildItem -Path . -Recurse -Filter "*.nupkg" | ForEach-Object {
            # Move each .nupkg file to the output folder
            Move-Item -Path $_.FullName -Destination $OutputFolder
            Write-Host "Moved $($_.FullName)"
        }
      shell: pwsh

    - name: Push to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./o*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
