name: Publish NuGet Package

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore "./NForza.Cyrus.sln"

    - name: Build the project
      run: dotnet build --configuration Release --output ./output "./NForza.Cyrus.sln"

    - name: Push to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./output/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
