name: Publish NuGet Package

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'  # Use your desired .NET version

    - name: Get current version
      id: get_version
      run: |
        # Extract the latest tag and generate the next revision number
        latest_tag=$(git describe --tags --match 'v[0-9]*' --abbrev=0 || echo "v1.0.0")
        echo "Latest tag: $latest_tag"
        major_minor=${latest_tag%.*}
        revision=${latest_tag##*.}
        next_revision=$((revision + 1))
        next_version="$major_minor.$next_revision"
        echo "Next version: $next_version"
        echo "next_version=$next_version" >> $GITHUB_ENV

    - name: Tag the new version
      run: |
        # Create a new tag with the incremented version
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git tag -a "$next_version" -m "Release $next_version"
        git push origin "$next_version"

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Pack the NuGet package
      run: dotnet pack --configuration Release --output ./output /p:PackageVersion=${{ env.next_version }}

    - name: Push to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./output/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
