name: Publish NuGet Package

on:
  workflow_dispatch:
  push:
    branches:
      - main  

env:
  BASE_VERSION: "1.0"
  NFORZA_CYRUS_NUSPEC: ./src/NForza.Cyrus.nuspec

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Calculate package version
      run: |
        echo "PACKAGE_VERSION=${BASE_VERSION}.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
      
    - name: Show package version
      run: |
        echo "Version: ${{ env.PACKAGE_VERSION }}"
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - uses: nuget/setup-nuget@v2
      with:
        nuget-version: 'latest'

    - name: Set NForza.Cyrus version
      run: sed -i 's/%VERSION%/${{ env.PACKAGE_VERSION }}/g' ${{ env.NFORZA_CYRUS_NUSPEC }}

    - name: Restore dependencies
      run: dotnet restore "./NForza.Cyrus.sln"

    - name: Build the project
      run: dotnet build --configuration Release "./NForza.Cyrus.sln" /p:PackageVersion=${{ env.PACKAGE_VERSION }}

    - name: Pack the Core project
      run: dotnet pack --configuration Release --output ./output "./src/NForza.Cyrus.Core/NForza.Cyrus.Core.csproj" /p:PackageVersion=${{ env.PACKAGE_VERSION }}

    - name: Pack the Generators project
      run: dotnet pack --configuration Release --output ./output "./src/NForza.Cyrus.Generators/NForza.Cyrus.Generators.csproj" /p:PackageVersion=${{ env.PACKAGE_VERSION }}

    - name: Pack the Abstractions project
      run: dotnet pack --configuration Release --output ./output "./src/NForza.Cyrus.Abstractions/NForza.Cyrus.Abstractions.csproj" /p:PackageVersion=${{ env.PACKAGE_VERSION }}

    - name: Pack the MassTransit project
      run: dotnet pack --configuration Release --output ./output "./src/NForza.Cyrus.MassTransit/NForza.Cyrus.MassTransit.csproj" /p:PackageVersion=${{ env.PACKAGE_VERSION }}

    - name: Push to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./output/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json

    - name: Restore the Cyrus metapackage
      run: |
        dotnet restore "./src/NForza.Cyrus.Metapackage/NForza.Cyrus.Metapackage.csproj" \
          /p:PackageVersion=${{ env.PACKAGE_VERSION }} \
          --source "./output/" \
          --source "https://api.nuget.org/v3/index.json"

    - name: Build the Cyrus metapackage
      run: dotnet build --no-restore --configuration Release --output ./output-meta "./src/NForza.Cyrus.Metapackage/NForza.Cyrus.Metapackage.csproj" /p:PackageVersion=${{ env.PACKAGE_VERSION }}     

    - name: Pack the Cyrus metapackage
      run: dotnet pack --no-build --no-restore --configuration Release --output ./output-meta "./src/NForza.Cyrus.Metapackage/NForza.Cyrus.Metapackage.csproj" /p:PackageVersion=${{ env.PACKAGE_VERSION }} /p:RestoreSources=./output
      
    - name: Push to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./output-meta/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
